version: "3"
services:
  monitoring:
    build: ./monitoring-service
    expose:
      - "5000"
    depends_on:
      - rabbitmq

  auth:
    build: ./auth-service
    expose:
      - "5000"

  alert:
    build: ./alert-service
    expose:
      - "5000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - monitoring
      - auth
      - alert
